apiVersion: v1
kind: Service
metadata:
  name: {{ include "leartech-ai-classifier.fullname" . }}
  labels:
    {{- include "leartech-ai-classifier.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
    protocol: TCP
  selector:
    {{- include "leartech-ai-classifier.selectorLabels" . | nindent 4 }}
